ZedShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using ZedShop.Core.DTOs.Order;
using ZedShop.Core.Services;
using ZedShop.Core.Services.Interface;
using ZedShop.DataLayer.Entities;

namespace ZedShop.Web.Controllers
{
   
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IProductService _productService;

        public OrderController(IOrderService orderService, IProductService productService)
        {
            _orderService = orderService;
            _productService = productService;
        }

        [Authorize]
        [Route("/MyOrders")]
        public IActionResult Index()
        {
            var username = User.Identity.Name;
            if (!string.IsNullOrEmpty(username))
            {
                Order order = _orderService.GetOpenOrder(username);

                List<OrderProductViewModel> OrderProductList= new List<OrderProductViewModel>();

                double total_price = 0;
                
                if(order != null)
                {
                    foreach (var item in order.OrderProducts)
                    {
                        var pro = _productService.GetProduct(item.ProductId);
                        OrderProductViewModel model = new OrderProductViewModel()
                        {
                            OrderId = order.Id,
                            ProdcutCount = item.Count,
                            SellPrice = item.Price * item.Count,
                            ProductId = pro.ProductId,
                            ProductName = pro.Name,
                            ProductImageName = pro.ProductImageName
                        };
                        total_price += item.Price * item.Count;
                        OrderProductList.Add(model);
                    }

                }

                OPTableViewModel oPTable = new OPTableViewModel()
                {
                    Items = OrderProductList,
                    TotalPrice = total_price
                };

                return View(oPTable);

            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [Route("/MyOrders/delete/{order_id}/{product_id}")]
        public JsonResult Index(int order_id, int product_id)
        {
            List<OrderProductViewModel> OrderProductList = new List<OrderProductViewModel>();

            double total_price = 0;

            var orderProduct = _orderService.GetOrderProduct(order_id, product_id);

            if (_orderService.DeleteProductFromOrder(order_id, product_id))
            {
                var data = _orderService.GetProductsOfOrder(order_id);
                
                foreach ( var item in data)
                {
                    OrderProductViewModel model = new OrderProductViewModel()
                    {
                        OrderId = item.OrdrId,
                        ProdcutCount = item.Count,
                        SellPrice = item.Price * item.Count,
                        ProductId = item.ProductId,
                        ProductName = item.Product.ProductImageName,
                        ProductImageName = item.Product.ProductImageName
                    };
                    total_price += item.Price * item.Count;
                    OrderProductList.Add(model);
                }
                _productService.IncreaseProductCount(product_id, orderProduct.Count);

            }

            OPTableViewModel oPTable = new OPTableViewModel()
            {
                Items = OrderProductList,
                TotalPrice = total_price
            };


            return Json(oPTable);
        }

            [Authorize]
        public ActionResult BuyProduct(OrderViewModel orderViewModel)
        {
            var username = User.Identity.Name;

            if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Home");
            }
            
            int orderId = -1;

            Product product = _productService.GetProduct(orderViewModel.ProductId);

            Order order = _orderService.GetOpenOrder(username);

            if (order == null)
            {
                orderId = _orderService.AddOrder(username);
            }
            else
            {
                orderId = order.Id;
                
                // check if product is exist in Order or not 
                if(order.OrderProducts.Any(o => o.ProductId == orderViewModel.ProductId))
                {
                    // if we have enough products decrease count and
                    // update db and return true
                    // else return false
                    if (_productService.DecreaseProductCount(product.ProductId, orderViewModel.Count))
                    {
                        _orderService.IncreaseProductCountOfOrder(product.ProductId, orderId, orderViewModel.Count);
                    }
                }
                else
                {
                    if (orderId != -1 && product != null)
                    {
                        OrderProduct orderProduct = new OrderProduct()
                        {
                            OrdrId = orderId,
                            ProductId = product.ProductId,
                            Count = orderViewModel.Count,
                            Price = product.SellPrice
                        };

                        // if we have enough products decrease count and
                        // update db and return true
                        // else return false
                        if (_productService.DecreaseProductCount(product.ProductId, orderViewModel.Count))
                        {
                            _orderService.AddProductToOrder(orderProduct);
                        }

                    }
                }

            }
            
            return RedirectToAction("Index");
        }
    }
}

ZedShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Net.Http.Json;
using ZedShop.Core.DTOs.Product;
using ZedShop.Core.Services.Interface;
using ZedShop.DataLayer.Context;
using ZedShop.DataLayer.Entities;

namespace ZedShop.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IUserService _userService;

        public ProductController(IProductService productService, IUserService userService)
        {
            _productService = productService;
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult AllProductsUserSearch(string userInput = "")
        {
            List<Product> products = new List<Product>();

            if (string.IsNullOrEmpty(userInput))
            {
                products = _productService.GetAllProducts();
            }
            else
            {
                products = _productService.GetAllProductsBySearchName(userInput);
            }

            List<ProductViewModel> productViewModels = new List<ProductViewModel>();

            foreach (var p in products)
            {

                productViewModels.Add(new ProductViewModel()
                {
                    Name = p.Name,
                    Description = p.Description,
                    IsActivate = p.IsActivate,
                    ProductId = p.ProductId,
                    ProductImageName = p.ProductImageName,
                    SellPrice = Convert.ToDouble(p.SellPrice),
                    Rating = getAvgValue(p.ProductRates.ToList())
                });


            }

            return PartialView("_BoxProductsContainer", productViewModels);
        }

        [HttpGet]
        public IActionResult AllProductsPartial(int? categoryId, int? orderId)
        {

            List<Product> products = new List<Product>();   
            if(categoryId == -1)
            {
                products = _productService.GetAllProducts();
            }
            else
            {
                products = _productService.GetAllProductsOfCategory(categoryId ?? 0);
            }

            switch (orderId)
            {
                case 1:
                    // cheap
                    products = products.OrderBy(p => p.SellPrice).ToList();
                    break; 

                case 2:
                    // expensive
                    products = products.OrderByDescending(p => p.SellPrice).ToList();
                    break;

                case 3:
                    // high rate
                    products = products.OrderByDescending(p =>
                    {
                        if (p.ProductRates == null || !p.ProductRates.Any())
                        {
                            return 1; // Default value for products without rates
                        }
                        else
                        {
                            return p.ProductRates.Average(r => r.Rate);
                        }

                    }).ToList();
                    break;

                default:
                    break;

            }


            List<ProductViewModel> productViewModels = new List<ProductViewModel>();

            foreach (var p in products)
            {
                productViewModels.Add(new ProductViewModel()
                {
                    Name = p.Name,
                    Description = p.Description,
                    IsActivate = p.IsActivate,
                    ProductId = p.ProductId,
                    ProductImageName = p.ProductImageName,
                    SellPrice = Convert.ToDouble(p.SellPrice),
                    Rating = getAvgValue(p.ProductRates.ToList())
                });

            }

            return PartialView("_BoxProductsContainer", productViewModels);
        }

        private float getAvgValue(List<ProductRate> rates)
        {
            if(rates.Any()) {
                return (float)rates.Select(r => r.Rate).Average();
            }
            else
            {
                return 1.0F;
            }
            
        }


        [Route("AllProduct")]
        public IActionResult AllProducts()
        {
            // select top 6 products
            var products = _productService.GetAllProducts(6);
            List<ProductViewModel> productViewModels = new List<ProductViewModel>();

            foreach (var p in products)
            {
                productViewModels.Add(new ProductViewModel()
                {
                    Name = p.Name,
                    Description = p.Description,
                    IsActivate = p.IsActivate,
                    ProductId = p.ProductId,
                    ProductImageName = p.ProductImageName,
                    SellPrice = Convert.ToDouble(p.SellPrice),
                    Rating = getAvgValue(p.ProductRates.ToList())
                });
            }

            ViewBag.Categories = _productService.GetAllCategory();

            #region SelectOrder

            List<SearchOrderProducts> allOrdersSelect = new List<SearchOrderProducts>();

            allOrdersSelect.Add(new SearchOrderProducts(1, "ارزان‌ترین"));
            allOrdersSelect.Add(new SearchOrderProducts(2, "گران‌ترین"));
            allOrdersSelect.Add(new SearchOrderProducts(3, "پرامتیازترین"));

            ViewBag.SelectOrder = allOrdersSelect;

            #endregion

            return View(productViewModels);
        }

        [Route("ShowProduct/{id}")]
        public IActionResult ShowProduct(int id)
        {
            var product = _productService.GetProduct(id);

            if (product == null)
            {
                return NotFound();
            }

            var comments = _productService.GetAllProductsComment(product.ProductId);

            List<Comment> pComments = comments.ToList();

            CommentViewModel commentViewModel = new CommentViewModel();

            var username = User.Identity.Name;
            if (!string.IsNullOrEmpty(username))
            {
                User user = _userService.GetUserByUserName(username);

                commentViewModel.PoroductId = product.ProductId;
                commentViewModel.UserId = user.UserId;

            }

            ShowProductViewModel proVM = new ShowProductViewModel()
            {
                Name = product.Name,
                Description = product.Description,
                Count = product.Count,
                DisCount = product.Count,
                IsActivate = product.IsActivate,
                ProductId = product.ProductId,
                ProductImageName = product.ProductImageName,
                SellPrice = Convert.ToDouble(product.SellPrice),
                ProductCategories = product.ProductCategories.ToList(),
                ProductComments = pComments,
                CommentViewModel = commentViewModel
            };

            return View(proVM);
        }

        [HttpPost]
        [Authorize]
        public IActionResult AddComment(ShowProductViewModel showProductViewModel)
        {
            CommentViewModel commentViewModel = showProductViewModel.CommentViewModel;

            if (commentViewModel == null)
            {
                return RedirectToAction("Index");
            }

            _productService.AddCommentToProduct(commentViewModel);

            return RedirectToAction("ShowProduct", new { id = commentViewModel.PoroductId });
        }


        [HttpPost]
        [Authorize]
        public IActionResult AddRating(ShowProductViewModel showProductViewModel)
        {
            if (showProductViewModel.Rating == 0)
            {
                return RedirectToAction("ShowProduct", new { id = showProductViewModel.ProductId });
            }

            int rate = showProductViewModel.Rating;

            var username = User.Identity.Name;
            if (!string.IsNullOrEmpty(username))
            {
                User user = _userService.GetUserByUserName(username);

                if (user != null)
                {
                    ProductRate OldRate = _productService.GetRateOfUser(user.UserId, showProductViewModel.ProductId);

                    if (OldRate != null)
                    {
                        // update old rate
                        OldRate.Rate = rate;
                        _productService.UpdateRateOfUser(OldRate);
                    }
                    else
                    {
                        //add new rate
                        RateViewModel rateViewModel = new RateViewModel()
                        {
                            UserId = user.UserId,
                            PoroductId = showProductViewModel.ProductId,
                            Rate = rate
                        };
                        _productService.AddRateToProduct(rateViewModel);

                    }
                }


            }

            return RedirectToAction("ShowProduct", new { id = showProductViewModel.ProductId });
        }
    }
}

ZedShop/Views/Product/AllProducts.cshtml
@model List<ZedShop.Core.DTOs.Product.ProductViewModel>
@{
    ViewData["Title"] = "مشاهده محصول";
}

<div class="search-container">
    <input type="text" id="product-search" style="margin-right:2%" placeholder="جستجو محصولات">
    <button type="button" disabled> <i class="icon-search" style="font-size: 20px;"></i></button>
    <select id="category-select" style="margin-right:2%; width:15%" onclick="LoadAllProducts()">
        <option value="-1">همه محصولات</option>
        @foreach (var item in ViewBag.Categories)
        {
            <option value="@item.Id">@item.Name</option>
        }

    </select>

    <select id="order-select" style="margin-right:2%; width:15%" onclick="LoadAllProducts()">
        <option value="-1">مرتب‌سازی بر اساس</option>
        @foreach (var item in ViewBag.SelectOrder)
        {
            <option value="@item.Id">@item.Name</option>
        }

    </select>

</div>


<div class="site-section" id="products-section">
    <div class="container">
        <div class="row" id="product-details-container">
            @{
                List<ZedShop.Core.DTOs.Product.ProductViewModel> products = Model;

                foreach (var item in products)
                {
                    <partial name="_BoxProducts" model="@item" />
                }
            }

            <script>
                $(document).ready(function () {
                    $("#product-search").on("keyup", function () {
                        var searchTerm = $(this).val().toLowerCase();  // Get search term and convert to lowercase

                        console.log("heeeree", searchTerm);

                    $.ajax({
                            url: '/Product/AllProductsUserSearch/', // Replace with your controller and action
                            data: { userInput: searchTerm }, // Send the product ID as a parameter
                        dataType: 'html',
                        success: function (data) {
                            console.log("heerere", data);
                            $('#product-details-container').html(data); // Insert the received HTML into the container
                        }
                    });
                    });
                });


                function LoadAllProducts() {
                    var selectElement = document.getElementById("category-select");
                    let id1 = selectElement.value;
                    var selectElement2 = document.getElementById("order-select");
                    let id2 = selectElement2.value;

                    $.ajax({
                        url: '/Product/AllProductsPartial/', // Replace with your controller and action
                        data: { categoryId: id1, orderId: id2 }, // Send the product ID as a parameter
                        dataType: 'html',
                        success: function (data) {
                            $('#product-details-container').html(data); // Insert the received HTML into the container
                        }
                    });
                }


            </script>
        </div>
    </div>
</div>

ZedShop/Views/Product/ShowProduct.cshtml
@* @model Tuple<ZedShop.Core.DTOs.Product.ShowProductViewModel, ZedShop.Core.DTOs.Product.CommentViewModel> *@

@model ZedShop.Core.DTOs.Product.ShowProductViewModel
@{
    ViewData["Title"] = "مشاهده محصول";
}
<div class="mspcardp">
    <form asp-controller="Order" asp-action="BuyProduct" method="post">
        <figure>
            <img src="/Products/image/@Model.ProductImageName" alt="Image" class="img-fluid">
        </figure>
        <input type="hidden" asp-for="ProductId" value="@Model.ProductId" />
        <h1>@Model.Name</h1>
        <div calss="rtldetail">
            <p class="price">قیمت کالا: @Model.SellPrice تومان</p>
            <p clsss="textproduct">تعداد کالا موجود: @Model.Count</p>

            @if (Model.ProductCategories != null)
            {
                string productCats = "";
                bool isFirstIteration = true;
                foreach (var item in Model.ProductCategories)
                {
                    if (!isFirstIteration)
                    {
                        productCats += "، ";
                    }
                    productCats += item.Category.Name;
                    isFirstIteration = false;
                }
                <p clsss="textproduct">نوع کالا: @productCats</p>
            }

            <label style="color:#666666;"> تعداد کالا: </label>
            @* <input type="number" asp-for="Count" class="pcount" name="overs" step="1" value="1"> *@
            <input type="number" asp-for="Count" class="pcount" step="1" id="overs" value="1">

            <p clsss="textproduct">توضیحات کالا: @Model.Description</p>



        </div>



        <button class="button-submit" type="submit">افزودن به سبد خرید <span class="icon-shopping-basket"></span></button>
        @* <p><button type="button" onclick="location.href='@Url.Action("BuyProduct", "Order", new { id = @Model.ProductId })'">افزودن به سبد خرید</button></p> *@
    </form>

    <br />

    <form asp-controller="Product" asp-action="AddRating" method="post">
        <input type="hidden" asp-for="ProductId" value="@Model.ProductId" />
        <div class="rating">
            <p style="margin-top:5px">امتیاز کالا:</p>
            <label for="star-1" class="stars">
                <input type="radio" id="star-1" name="rating" value="1">
                <span class="icon-star" id="icon-star-1"></span>
            </label>
            <label for="star-2" class="stars">
                <input type="radio" id="star-2" name="rating" value="2">
                <span class="icon-star" id="icon-star-2"></span>
            </label>
            <label for="star-3" class="stars">
                <input type="radio" id="star-3" name="rating" value="3">
                <span class="icon-star" id="icon-star-3"></span>
            </label>
            <label for="star-4" class="stars">
                <input type="radio" id="star-4" name="rating" value="4">
                <span class="icon-star" id="icon-star-4"></span>
            </label>
            <label for="star-5" class="stars">
                <input type="radio" id="star-5" name="rating" value="5">
                <span class="icon-star" id="icon-star-5"></span>
            </label>

            <input type="hidden" asp-for="@Model.Rating">
            <button type="submit" class="btn btn-outline-info" style="height:20%">ثبت امتیاز ✓</button>

        </div>
    </form>

    <div class="all-comments">
        <br />
        <h3>دیدگاه‌های کاربران:</h3>
        <br />
        @* <a href="#" class="add-comment">افزودن نظر جدید ✏️</a> *@

        @Html.Partial("_CommentPopUp")

        <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#commentModal">
            افزودن دیدگاه جدید ✏️
        </button>
        <br />
        <br />




        @if (Model.ProductComments != null)
        {
            @foreach (var item in Model.ProductComments)
            {
                <div class="comment-container">
                    <img src="/UserAvatar/@item.User.UserAvatar" alt="User Avatar" class="user-avatar">
                    <div class="comment-content">
                        <h4 class="comment-author">@item.User.UserName</h4>
                        <p class="comment-text">@item.CommentText</p>
                        <span class="comment-date">@item.CommentDate</span>
                    </div>
                </div>
            }
        }





    </div>

</div>



<script>
    var input = document.querySelector("[id='overs']");

    input.addEventListener("input", function () {
        var value = this.value;
        if (value < 1) {
            this.value = 1;
        }
        if (value > @Model.Count) {
            this.value = @Model.Count;
        }
    })
</script>

<script>

    $(document).ready(function () {
        $('input[type="radio"]').click(function () {
            let val = this.value;
            
            for (let i = 1; i <= val; i++) {
                document.getElementById("icon-star-" + i).style.color = 'gold';
            }

            for (let i = 5; i > val; i--) {
                document.getElementById("icon-star-" + i).style.color = 'gray';
            }
            
        });

    });

</script>


<script>
    $(document).ready(function () {
        $('#commentModal').on('hidden.bs.modal', function (e) {
            // Clear the comment form after modal is closed (optional)
            $(this).find('form').trigger("reset");
        });
    });

</script>

ZedShop/Views/Product/_BoxProductsContainer.cshtml
@using ZedShop.Core.DTOs.Product
@model List<ZedShop.Core.DTOs.Product.ProductViewModel>

@{
    List<ProductViewModel> products = Model;

    foreach (var item in products)
    {
        <partial name="_BoxProducts" model="@item" />
    }
}

ZedShop/Views/Product/_CommentPopUp.cshtml
@model ZedShop.Core.DTOs.Product.ShowProductViewModel

<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="display: flex; justify-content: space-between; align-items: center;">
                <h5 class="modal-title" id="commentModalLabel">افزودن دیدگاه جدید</h5>
                <button style="margin-right:55%" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="AddComment" asp-controller="Product">
                    <input type="hidden" asp-for="@Model.CommentViewModel.UserId" value="@Model.CommentViewModel.UserId" />
                    <input type="hidden" asp-for="@Model.CommentViewModel.PoroductId" value="@Model.CommentViewModel.PoroductId" />

                    <div class="form-group">
                        <label asp-for="@Model.CommentViewModel.Content">دیدگاه</label>
                        <textarea class="form-control" asp-for="@Model.CommentViewModel.Content" rows="5"></textarea>
                    </div>
                    <div style="width:100%; text-align:center;">
                        <button type="submit" class="btn btn-info">ارسال دیدگاه</button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</div>