ZedShop/Areas/Admin/Models/UserViewModel/UserViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using ZedShop.DataLayer.Entities;

namespace ZedShop.Web.Areas.Admin.Models.UserViewModel
{
    public class UserViewModel
    {
        public int UserId { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [DisplayName("نام کاربری")]
        [MaxLength(200, ErrorMessage = "{0} نمیتواند بیشتر از {1} باشد")]
        public string UserName { get; set; } = string.Empty;

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [DisplayName("ایمیل")]
        [MaxLength(200, ErrorMessage = "{0} نمیتواند بیشتر از {1} باشد")]
        [EmailAddress(ErrorMessage = "ایمیل وارد شده معتبر نمی‌باشد")]
        public string Email { get; set; } = string.Empty;

        [DisplayName("کلمه عبور")]
        [MaxLength(200, ErrorMessage = "{0} نمیتواند بیشتر از {1} باشد")]
        public string Password { get; set; } = string.Empty;

        [DisplayName("آواتار")]
        [MaxLength(200, ErrorMessage = "{0} نمیتواند بیشتر از {1} باشد")]
        public string UserAvatar { get; set; } = string.Empty;

        [DisplayName("نقش کاربری")]
        [MaxLength(200, ErrorMessage = "{0} نمیتواند بیشتر از {1} باشد")]
        public string RoleName { get; set; } = string.Empty;

        public IFormFile? ProfileFile { get; set; }


        public GenderTypes Gender { get; set; }

        public bool IsActive { get; set; } = false;

        public bool IsBan { get; set; } = false;



    }
}

ZedShop/Areas/Admin/Controllers/ManageUsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.CodeAnalysis;
using ZedShop.Core.DTOs.Product;
using ZedShop.Core.Services;
using ZedShop.Core.Services.Interface;
using ZedShop.DataLayer.Entities;
using ZedShop.Web.Areas.Admin.Models.UserViewModel;
using ZedShop.Core.CustomAuthorization;

namespace ZedShop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "2 , 3")] // 2 is admin and 3 is owner

    public class ManageUsersController : Controller
    {
        private readonly IUserService _userService;

        private int pageCount, currentPage, allUserCount, numberPerPage, roleId, filterId;

        private readonly List<FilterBaseViewModel> filtersBase = new List<FilterBaseViewModel>();

        public ManageUsersController(IUserService userService)
        {
            _userService = userService;


            filtersBase.Add(new FilterBaseViewModel(-1, "همه کاربران"));
            filtersBase.Add(new FilterBaseViewModel(0, "حذف شده‌"));
            filtersBase.Add(new FilterBaseViewModel(1, "مسدود شده‌"));
            filtersBase.Add(new FilterBaseViewModel(2, "غیر فعال"));

            // paging initialization

            numberPerPage = 10;
            currentPage = 1;
            allUserCount = userService.GetAllUsersCount(roleId, filterId);
            pageCount = (int)Math.Ceiling((double)allUserCount / numberPerPage);

        }


        public IActionResult Index()
        {
            roleId = -1;
            filterId = -1;
            List<UserViewModel> userViews = GetUsers(roleId , filterId);

            var roles = _userService.GetAllRoles();
            ViewBag.Roles = roles;

            currentPage = 1;

            ViewBag.Filters = filtersBase;
            ViewBag.NumberOfPage = pageCount;
            ViewBag.CurrentPage = currentPage;
            ViewBag.RoleId = roleId;
            ViewBag.FilterId = filterId;

            return View(userViews);
        }

        [HttpGet]
        public IActionResult AllUsersOfRoleFilter(int _roleId, int _filterId)
        {

            List<UserViewModel> userViews = GetUsers(_roleId, _filterId);

            currentPage = 1;

            ViewBag.NumberOfPage = pageCount;
            ViewBag.CurrentPage = currentPage;
            ViewBag.RoleId = roleId;
            ViewBag.FilterId = filterId;

            return PartialView("_UsersTable", userViews);
        }

        public List<UserViewModel> GetUsers(int _roleId, int _filterId)
        {
            this.roleId = _roleId;
            this.filterId = _filterId;
            var users = _userService.GetAllUsersPagedRole(currentPage, numberPerPage, roleId, filterId);

            List<UserViewModel> userViews = new List<UserViewModel>();

            foreach (var user in users)
            {
                userViews.Add(new UserViewModel
                {
                    UserId = user.UserId,
                    UserName = user.UserName,
                    RoleName = user.Role.Name,
                    Email = user.Email,
                    Gender = user.gender,
                    IsActive = user.IsActive,
                    IsBan = user.IsBan
                });
            }

            allUserCount = _userService.GetAllUsersCount(roleId, filterId);
            pageCount = (int)Math.Ceiling((double)allUserCount / numberPerPage);

            return userViews;
        }

        [OwnerFilter] // just owner of site
        [Route("/Admin/ManageUsers/EditUserRole/{userId}")]
        [HttpGet]
        public IActionResult EditUserRole(int userId)
        {

            UserRoleViewModel userRole = new UserRoleViewModel();
            var user = _userService.GetUserByIdWithRole(userId);

            if (user != null)
            {
                userRole.UserName = user.UserName;
                userRole.UserId = user.UserId;
                userRole.RoleName = user.Role.Name;
                userRole.RoleId = user.RoleId;
            }

            List<Role> roles = _userService.GetAllRoles();

            ViewBag.Roles = roles;


            return View(userRole);

        }

        [OwnerFilter] // just owner of site
        [Route("/Admin/ManageUsers/EditUserRole/{userId}")]
        [HttpPost]
        public IActionResult EditUserRole(UserRoleViewModel userRole)
        {

            if (!ModelState.IsValid)
            {

                return View(userRole);
            }

            User user = _userService.GetUserById(userRole.UserId);

            // check user is notnull
            if (user != null)
            {
                // Todo: implement site policy

                if (_userService.IsRoleExist(userRole.SelectedRoleId))
                {
                    user.RoleId = userRole.SelectedRoleId;

                    _userService.UpdateUser(user, null);

                    return RedirectToAction("Index");


                }
            }


            return View(userRole);


        }



        //[Authorize]
        [Route("/Admin/ManageUsers/EditUser/{userId}")]
        [HttpGet]
        public IActionResult EditUser(int userId)
        {

            var user = _userService.GetUserById(userId);

            UserViewModel userViewModel = new UserViewModel();

            if (user != null)
            {
                userViewModel.UserId = userId;
                userViewModel.UserName = user.UserName;
                userViewModel.Email = user.Email;
                userViewModel.Password = user.Password;
                userViewModel.UserAvatar = user.UserAvatar;
                userViewModel.Gender = user.gender;
                userViewModel.IsActive = user.IsActive;
                userViewModel.IsBan = user.IsBan;

            }


            return View(userViewModel);
        }


        //[Authorize]
        [Route("/Admin/ManageUsers/EditUser/{userId}")]
        [HttpPost]
        public IActionResult EditUser(UserViewModel userViewModel)
        {

            if (!ModelState.IsValid)
            {

                return View(userViewModel);
            }

            User user = _userService.GetUserById(userViewModel.UserId);

            // check user is notnull
            if (user != null)
            {

                // check Email is changed and already exist
                if (!(!user.Email.Equals(userViewModel.Email) && _userService.IsExistEmail(user.Email)))
                {

                    // check UserName is changed and already exist
                    if (!(!user.UserName.Equals(userViewModel.UserName) && _userService.IsExistUserName(user.UserName)))
                    {
                        user.Email = userViewModel.Email;
                        user.UserName = userViewModel.UserName;
                        user.IsActive = userViewModel.IsActive;
                        user.IsBan = userViewModel.IsBan;

                        _userService.UpdateUser(user, userViewModel.ProfileFile);

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("UserName", "نام کاربری تکراری است!!");
                    }
                }
                else
                {
                    ModelState.AddModelError("Email", "ایمیل تکراری است!!");

                }

            }
            else
            {
                ModelState.AddModelError("Email", "کاربری با مشخصات فوق یافت نشد");
            }


            return View(userViewModel);
        }


        //[Authorize]
        [Route("/Admin/ManageUsers/BanUser/{userId}")]
        [HttpGet]
        public ActionResult BanUser(int userId)
        {
            bool resault = _userService.BanUser(userId);

            return Json(new { resault = resault });
        }

        [HttpGet]
        public ActionResult DeleteUser(int id)
        {
            _userService.DeleteUser(id);
            return Json(new { success = true });
        }

        [HttpGet]
        public IActionResult ChangePage(int _roleId , int _filterId, int pageNumber = 1)
        {
            this.roleId = _roleId;
            this.filterId = _filterId;
            currentPage = pageNumber;
            List<UserViewModel> userViews = GetUsers(roleId, filterId);

            ViewBag.NumberOfPage = pageCount;
            ViewBag.CurrentPage = currentPage;
            ViewBag.RoleId = roleId;
            ViewBag.FilterId = filterId;

            return PartialView("_UsersTable", userViews);
        }
    }
}

ZedShop/Areas/Admin/Views/ManageUsers/EditUser.cshtml
@model ZedShop.Web.Areas.Admin.Models.UserViewModel.UserViewModel

@{
    ViewData["Title"] = "ویرایش کاربر";
    Layout = "~/areas/admin/views/shared/_AdminLayout.cshtml";

}

<div class="col-12">
    <div class="card">
        <div class="card-body">

            <h4 class="card-title"><strong> ویرایش کاربر </strong></h4>
            <form asp-action="EditUser" asp-controller="ManageUsers" method="post" enctype="multipart/form-data">
                @if (TempData["Message"] != null)
                {
                    <div class="alert alert-danger">
                        <span>
                            @TempData["Message"]
                        </span>
                    </div>
                }


                <div class="row-form-container">



                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="UserId" class="form-control" />
                    <input type="hidden" asp-for="UserAvatar" class="form-control" />

                    <div class="simple-center-div" style="margin-top:20px; margin-bottom:20px;">
                        <figure>
                            <img src="/UserAvatar/@Model.UserAvatar" alt="Image" class="edit-user-img">
                        </figure>
                    </div>

                    <div class="row-form">
                        <div class="left" style="width: 50%;">
                            <div class="form-group">
                                <label asp-for="UserName" class="control-label"></label>
                                <input asp-for="UserName" class="form-control" />
                                <span asp-validation-for="UserName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label>انتخاب تصویر</label>
                                <input asp-for="ProfileFile" type="file">
                            </div>
                        </div>

                        <div class="right" style="width: 50%;">
                            <div class="form-group">
                                <label asp-for="Email" class="control-label"></label>
                                <input asp-for="Email" class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>

                            <div class="form-auth-row">
                                <label for="IsActive" class="ui-checkbox">
                                    <input asp-for="IsActive" type="checkbox">
                                    <span class="ui-checkbox-check" ></span>
                                </label>
                                <label for="IsActive">اکانت فعال شده</label>
                            </div>

                            <div class="form-auth-row">
                                <label for="IsBan" class="ui-checkbox">
                                    <input asp-for="IsBan" type="checkbox">
                                    <span class="ui-checkbox-check"></span>
                                </label>
                                <label for="IsBan">اکانت مسدود شده</label>
                            </div>

                        </div>
                    </div>


                    <div class="simple-center-div" style="margin-top:20px; margin-bottom:20px;">
                        <div class="form-group">
                            <input type="submit" value="ذخیره" class="btn btn-success" />
                            <button class="btn btn-warning btn-sm" asp-action="Index">انصراف</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

ZedShop/Areas/Admin/Views/ManageUsers/EditUserRole.cshtml
@model ZedShop.Web.Areas.Admin.Models.UserViewModel.UserRoleViewModel

@{
    ViewData["Title"] = "ویرایش نقش کاربر";
    Layout = "~/areas/admin/views/shared/_AdminLayout.cshtml";

}

<div class="col-12">
    <div class="card">
        <div class="card-body">

            <h4 class="card-title"><strong> ویرایش کاربر </strong></h4>
            <form asp-action="EditUserRole" asp-controller="ManageUsers" method="post">


                <div class="row-form-container">


                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="UserId" class="form-control" />

                    <div class="row-form">
                        <div class="left" style="width: 50%;">
                            <div class="form-group">
                                <p><strong> نام کاربری: @Model.UserName</strong></p>
                                <p><strong> نقش کاربر: @Model.RoleName</strong></p>
                            </div>

                        </div>

                        <div class="right" style="width: 50%;">
                            <div class="form-group" style="display: flex;">
                                <p style="margin-left:5%"><strong> نقش جدید:</strong></p>
                                <select id="myDropdown" class="chosen-select" asp-for="SelectedRoleId" style="width:50%">
                                    @foreach (var item in ViewBag.Roles)
                                    {
                                        <option value="@item.Id">@item.Name</option>
                                    }
                                </select>
                            </div>

                        </div>
                    </div>


                    <div class="simple-center-div" style="margin-top:20px; margin-bottom:20px;">
                        <div class="form-group">
                            <input type="submit" value="ذخیره" class="btn btn-success" />
                            <button class="btn btn-warning btn-sm" asp-action="Index">انصراف</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

ZedShop/Areas/Admin/Views/ManageUsers/Index.cshtml
@model List<ZedShop.Web.Areas.Admin.Models.UserViewModel.UserViewModel>
@{
    ViewData["Title"] = "مدیریت کاربران";
    Layout = "~/areas/admin/views/shared/_AdminLayout.cshtml";
}

@* @if (TempData["StatusMessage"] != null) https://localhost:7062/Admin/ManageUsers/Index
{
    <div class="alert alert-success text-center" role="alert">
        @TempData["StatusMessage"]
    </div>
} *@
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div style="display:flex;">

                    <p class="card-title"> <strong>کاربران</strong> </p>

                    <p class="card-title" style="margin-top:15px;margin-right:2%;font-size:16px; "> دسته‌بندی:  </p>
                    <select id="role-select" style="margin-right:5px; width:15%" onclick="LoadUserByRoleFilter()">

                        <option value="-1">همه کاربران</option>
                        @foreach (var item in ViewBag.Roles)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                      
                    </select>

                    <p class="card-title" style="margin-top:15px;margin-right:2%;font-size:16px; "> فیلتر:  </p>
                    <select id="filter-select" style="margin-right:5px; width:15%" onclick="LoadUserByRoleFilter()">

                        @foreach (var item in ViewBag.Filters)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }

                    </select>

                </div>


                @if (ViewBag.Message != null)
                {
                    @foreach (var item in ViewBag.Message)
                    {
                        <div class="alert alert-info">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
                            <h3 class="text-info"><i class="fa fa-exclamation-circle"></i> Information</h3>
                            @item
                        </div>
                    }
                }
                <div id="basicgrid" class="m-t-40 jsgrid" style="position: relative; height: 750px; width: 100%;">
                    <div class="jsgrid-grid-header jsgrid-header-scrollbar">
                        <table class="jsgrid-table table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th style="width:10%">
                                        نام کاربری
                                    </th>
                                    <th style="width:18%">
                                        ایمیل
                                    </th>
                                    <th style="width:8%; text-align:center;">
                                        نقش کاربری
                                    </th>
                                    <th style="width:5%; text-align:center;">
                                        جنسیت
                                    </th>
                                    <th style="width:5%; text-align:center;">
                                        تایید ایمیل
                                    </th>
                                    <th style="width:5%; text-align:center;">
                                        مسدود
                                    </th>
                                    <th style="width:20%; text-align:center;">
                                        اقدامات
                                    </th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <div id="tableofusercontent">
                        @Html.Partial("_UsersTable")
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<script>
    function updateTableData(roleId, filterId, pageNum) {
        $.ajax({
            url: '/Admin/ManageUsers/ChangePage/', // controller and action
            data: { _roleId: roleId, _filterId: filterId, pageNumber: pageNum, }, // Send the userInput as a parameter
            dataType: 'html',
            success: function (data) {

                $('#tableofusercontent').html(data); // Insert the received HTML into the container
            }
        });
    }

</script>


<script>
    function DeleteUser(id) {
        if (confirm("آیا از حذف مطمین هستید؟")) {
            $.get("/Admin/ManageUsers/DeleteUser/" + id,
                function () {
                    var myobj = document.getElementById(id);
                    myobj.remove();
                });
        }
    }

    function BanUser(id) {
        if (confirm("آیا از مسدود کردن کاربر مطمین هستید؟")) {
            console.log("deeff", id);

            $.get("/Admin/ManageUsers/BanUser/" + id,
                function (response) {
                    console.log("deeff", response);
                    var myobj = document.getElementById('ban_' + id);
                    if (response.resault) {
                        myobj.textContent = "بله";
                    } else {
                        myobj.textContent = "خیر";
                    }


                });
        }
    }

</script>

<script>
    function LoadUserByRoleFilter() {

        var selectElement = document.getElementById("role-select");
        var filterElement = document.getElementById("filter-select");

        let id1 = selectElement.value;
        let id2 = filterElement.value;

        $.ajax({
            url: '/Admin/ManageUsers/AllUsersOfRoleFilter/', //controller and action
            data: { _roleId: id1, _filterId: id2 }, // Send the product ID as a parameter
            dataType: 'html',
            success: function (data) {
                $('#tableofusercontent').html(data); // Insert the received HTML into the container
            }
        });
    }
</script>

ZedShop/Areas/Admin/Views/ManageUsers/_UsersTable.cshtml
@using ZedShop.Web.Areas.Admin.Models.UserViewModel
@model List<ZedShop.Web.Areas.Admin.Models.UserViewModel.UserViewModel>

<div class="jsgrid-grid-body">
    <table class="jsgrid-table table table-striped table-hover">
        <tbody id="userstable">
            @if (Model != null)
            {
                @foreach (var item in Model)
                {
                    <tr id="@item.UserId">

                        <td style="width:10%">
                            @item.UserName
                        </td>
                        <td style="width:18%">
                            @item.Email
                        </td>
                        <td style="width:8%; text-align:center">
                            @item.RoleName
                        </td>
                        <td style="width:5%; text-align:center">
                            @item.Gender.ToString()
                        </td>
                        <td style="width:5%; text-align:center">
                            @if (item.IsActive)
                            {
                                <p>فعال</p>
                            }
                            else
                            {
                                <p>غیرفعال</p>
                            }

                        </td>
                        <td id='ban_@item.UserId' style="width:5%; text-align:center">

                            @if (!item.IsBan)
                            {
                                <p>خیر</p>
                            }
                            else
                            {
                                <p>مسدود</p>
                            }
                        </td>
                        <td style="width:20%; text-align:center">
                            <a  class="btn btn-primary btn-sm" href="/Admin/ManageUsers/EditUser/@item.UserId">ویرایش</a>
                            <a class="btn btn-primary btn-sm" href="/Admin/ManageUsers/EditUserRole/@item.UserId">ویرایش نقش</a>
                            <button class="btn btn-warning btn-sm" onclick="BanUser(@item.UserId)">مسدود </button>
                            <button class="btn btn-danger btn-sm" onclick="DeleteUser(@item.UserId)">حذف </button>
                            

                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<div class="jsgrid-pager-container">
    <div class="jsgrid-pager">
        صفحه:


        @if (ViewBag.CurrentPage == 1 || ViewBag.NumberOfPage == 0)
        {
            <span class="jsgrid-pager-nav-button-off jsgrid-pager-nav-inactive-button">
                <a class="disabled">اولین</a>
            </span>
            <span class="jsgrid-pager-nav-button-off jsgrid-pager-nav-inactive-button">
                <a class="disabled">قبلی</a>
            </span>
        }
        else
        {
            <span class="jsgrid-pager-nav-button jsgrid-pager-nav-inactive-button">
                <a href="javascript:updateTableData(@ViewBag.RoleId,@ViewBag.FilterId,1);">اولین</a>
            </span>
            <span class="jsgrid-pager-nav-button jsgrid-pager-nav-inactive-button">
                <a href="javascript:updateTableData(@ViewBag.RoleId,@ViewBag.FilterId,@ViewBag.CurrentPage-1);">قبلی</a>
            </span>
        }


        @if (ViewBag.CurrentPage > 1)
        {
            <span class="jsgrid-pager-page"><a href="javascript:updateTableData(@ViewBag.RoleId,@ViewBag.FilterId,@ViewBag.CurrentPage-1);">@((ViewBag.CurrentPage - 1))</a></span>
        }

        <span class="jsgrid-pager-page jsgrid-pager-current-page">@ViewBag.CurrentPage</span>

        @if (ViewBag.CurrentPage < ViewBag.NumberOfPage)
        {
            <span class="jsgrid-pager-page"><a href="javascript:updateTableData(@ViewBag.RoleId,@ViewBag.FilterId,@ViewBag.CurrentPage+1);">@((ViewBag.CurrentPage + 1))</a></span>
        }


        @if (ViewBag.CurrentPage == ViewBag.NumberOfPage ||  ViewBag.NumberOfPage == 0)
        {
            <span class="jsgrid-pager-nav-button-off jsgrid-pager-nav-inactive-button">
                <a class="disabled">بعدی</a>
            </span>
            <span class="jsgrid-pager-nav-button-off jsgrid-pager-nav-inactive-button">
                <a class="disabled">آخرین</a>
            </span>

        }
        else
        {
            <span class="jsgrid-pager-nav-button jsgrid-pager-nav-inactive-button">
                <a href="javascript:updateTableData(@ViewBag.RoleId,@ViewBag.FilterId, @ViewBag.CurrentPage+1);">بعدی</a>
            </span>
            <span class="jsgrid-pager-nav-button"><a href="javascript:updateTableData(@ViewBag.RoleId, @ViewBag.FilterId,@ViewBag.NumberOfPage);">آخرین</a></span>
        }


        &nbsp;&nbsp; @ViewBag.CurrentPage از @ViewBag.NumberOfPage
    </div>
</div>